### ISSUE TITLE
Can I port Essentials to Minecraft Pocket Edition server PocketMine-MP? 

### ISSUE THREAD

**Issue by ghost** [essentials/EssSupport#2]
Hello can I port this awesome project to MCPE Server PocketMine-MP? Thanks a lot! 
@khobbits @ElgarL @GunfighterJ

**Comment by chrisgward** [comment]
You may, but can you? No idea.

**Comment by ghost** [comment]
@chrisgward I already did but MinecraftForums moderator make me to get permission. Thanks! :D
EDIT by Chris: Removed ad

**Comment by ghost** [comment]
Thanks! :D
