### ISSUE TITLE
Port to Minecraft PE (PocketMine Servers)

### ISSUE THREAD

**Issue by iksaku** [essentials/EssSupport#3]
Hi devs!

I'm iksaku, and I was working with @kvwang98 some time with his Essentials for Minecraft PE, but now I wanna get permission to make my own version (since he no longer works on it), I know that he got permission but I want to do this correctly.

Thanks!

**Comment by chrisgward** [comment]
As long as you abide by the license, you don't even need to ask

**Comment by iksaku** [comment]
Whoa! Thanks! I will show you the progress later... Or can I post it here? (Okey maybe not here :P)

**Comment by iksaku** [comment]
Hi there! Well I'm working really hard on it and I trying to make it like the PC version... but MCPE have tons of limitations for me to port awesome features like Fly in survival... Anyways, [here's](https://github.com/LegendOfMCPE/EssentialsPE) our progress (and by our I mean my whole team of devs).

Thank you guys for let me port it, this is become a really great project for me and a huge challenge for every plugin developer of PocketMine-MP... I want to know if there're any issues with it (Licenses or anything) and I will try to fix them in order to continue the project and make it public.

Greetings!

**Comment by khobbits** [comment]
Looks fine so far.

As long as you don't use "Essentials" on its own ("EssentialsPE" is fine), and keep the GPL3 licence, you are doing all you need to to keep us happy.

**Comment by iksaku** [comment]
Thank you very much! I'm really excited on this project :D

-----Mensaje original-----
De: KHobbits
Enviado: 04/08/2014 05:33 p.m.
Para: essentials/EssSupport
CC: Jorge González
Asunto: Re: [EssSupport] Port to Minecraft PE (PocketMine Servers) (#3)

Looks fine so far.

As long as you don't use "Essentials" on its own ("EssentialsPE" is fine), and keep the GPL3 licence, you are doing all you need to to keep us happy.
