### ISSUE TITLE
Essentials for Minecraft PE

### ISSUE THREAD

**Issue by ghost** [essentials/EssSupport#4]
Hi, 
Could you please put my PE version of Essentials to your homepage please? 
And I really wanna join your team. Maybe you can create a new repo in this organization. 
Thanks alot! :D

**Comment by chrisgward** [comment]
I can't even find it...

**Comment by ghost** [comment]
@chrisgward Cuz I haven't upload it yet.

**Comment by chrisgward** [comment]
How can we look at something which doesn't exist?

**Comment by ghost** [comment]
@chrisgward Let me upload to github now. XD

**Comment by ghost** [comment]
@chrisgward Done! :D http://github.com/kvwang98/EssentialsPE

**Comment by chrisgward** [comment]
I have some issues with your license, which may be in breach of the license of Essentials, and perhaps that of the LGPL in itself (additionally, if you don't want people to sell it, why use the LGPL, why not GPL?)

**Comment by ghost** [comment]
@chrisgward XD I am  not good at law, I can change things if you need me to and I can transfer this repo to essentials team. :)

**Comment by snowleo** [comment]
What is the difference between
https://github.com/kvwang98/EssentialsPE
and
https://github.com/LegendOfMCPE/EssentialsPE

**Comment by ghost** [comment]
@chrisgward @snowleo iksaku was teamed with me but be broke up and he make himself's version. 
Of course I didn't give him permission to copy my work, I made ess for MCPE years ago and recently I updated to new version and deleted my old version.

**Comment by chrisgward** [comment]
I'm not really the one with the autority to transfer the repository, but with the current licensing setup it's going to be hard to actually decide. (EDIT: oops, wrong repo)
      1: You may NOT copy this plugin's idea/concept and you shouldn't copy the way its working.
This is interesting to add, since this isn't a legal statement without a patent either.

**Comment by ghost** [comment]
@chrisgward Please tell me what should I do sir, I promise I will change things until I completely follow the rules.

**Comment by snowleo** [comment]
We have to discuss this in the team.

**Comment by ghost** [comment]
@chrisgward @snowleo I can change the licence. I will follow your rules. :)

**Comment by ghost** [comment]
@snowleo Thanks a lot dude!! Give me a hug!!! :D

**Comment by ghost** [comment]
@snowleo You know that PocketMine server is now using Bukkit structure, even plugins.

**Comment by ghost** [comment]
@snowleo I am afraid that I can't join your team anymore,I made some mistakes. Sorry, bye.

**Comment by ghost** [comment]
@snowleo I am afraid that I can't join your team anymore,I made some mistakes. Sorry, bye.

**Comment by iksaku** [comment]
I'm really sorry to keep this, but the truth is that Kevin gave me his version and tired to make me upload it as my own, when he firstly quitted, I don't wanted to keep his work, and I made my own project... I'm 100% independent from him, and I no longer have contact with him... I don't copy his work, he copied mine :/ anyways, this is not relevant for me, but I just wan't to let you know the truth :wink: 

Oh, and good luck with what is happening to bukkit, I think that it will not affect you :smile_cat:
